### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by kosletr** [Morzeux/HttpParamsDataset#1]
Nice work! Could you please add a LICENSE file (preferably MIT) so that I can use your dataset for a project of mine? 
I will not forget to mention your name and give you credits.

Thank you in advance!

**Comment by Morzeux** [comment]
Hi kosletr, of course, no problem. MIT license added. Feel free to use it as you please. I'm glad it can serve further :) 

https://github.com/Morzeux/HttpParamsDataset/blob/master/LICENSE
